### ISSUE TITLE
SSL for Docker

### ISSUE THREAD

**Issue by s1lviu** [Kopano-dev/kwmserver#1]
Hello!

I have used docker, but I cannot achieve how to install let's encrypt or Cloudflare certificates without editing the docker image.

Any suggestions for this?

Thanks!

**Comment by fbartels** [comment]
Hi @s1lviu,

I would recommend to realise ssl by putting a reverse proxy in front of kwmserver. You usually also want to expose other services on the same machine so the overhead through this should be minimal.

You can find the documentation for our webrtc app called "Kopano Meet" at https://documentation.kopano.io/kopano_meet_manual/index.html. Meet is a static webapp (designed as a pwa) that makes use of kwmserver and a few more components from our stack.

Out of interest for what kind of projects to you want to use kwmserver?

**Comment by s1lviu** [comment]
Yep, I have tried with [Caddy](https://i.imgur.com/NYzpPFk.png), but I receive 

> [SSL handshake failed](https://i.imgur.com/Q7q6A0I.png)

I don't know why I receive that SSL error, the certs are downloaded from the Cloudflare account and secondly, I don't know how to link that Caddy config to point into docker `root ./www`

I want to use it for Mattermost and my experience with Caddy is near 0 - from your docs I have discovered it, haha and with docker is a little. 

If you can give me a hint of how to put the kwmserver behind Cloudflare using Caddy or nginx would be great

**Comment by fbartels** [comment]
There is an example for Nginx in the documentation of our Mattermost plugin: https://documentation.kopano.io/kopano_mattermost_manual/webmeetings.html

**Comment by s1lviu** [comment]
> There is an example for Nginx in the documentation of our Mattermost plugin: https://documentation.kopano.io/kopano_mattermost_manual/webmeetings.html

Oh, great. 
I have tested it, works like a charm. But a small bug with the hang up button that is not visible on desktop. 

Thank you

**Comment by fbartels** [comment]
> But a small bug with the hang up button that is not visible on desktop.

Yes, it is known that there is an overlap with the search bar. Eventually we will replace/enhance the current approach by the new Meet and will resolve it then.
