### ISSUE TITLE
Runtime Panic starting kwmserverd when --iss not specified

### ISSUE THREAD

**Issue by tech348712013870132** [Kopano-dev/kwmserver#4]
When will the iss runtime panic bug be fixed within the lastest kwmserver docker image?
In the forum I see that a fix is already committed but at which point in time does it get into the official kwmserver docker image?

--> https://forum.kopano.io/topic/2805/runtime-panic-starting-kwmserverd-when-iss-not-specified

**Comment by fbartels** [comment]
Hi @tech348712013870132,

there currently is not tag in git which would include the referenced commit. Generally speaking you can prevent the issue by specifying an issuer (which could be localhost).
